// flow-typed signature: 0ad05da3561f11ceb1a07503caa634c7
// flow-typed version: <<STUB>>/express-ipfilter_v^0.3.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-ipfilter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "express-ipfilter" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "express-ipfilter/example/app" {
  declare module.exports: any;
}

declare module "express-ipfilter/example/routes/index" {
  declare module.exports: any;
}

declare module "express-ipfilter/example/routes/users" {
  declare module.exports: any;
}

declare module "express-ipfilter/Gruntfile" {
  declare module.exports: any;
}

declare module "express-ipfilter/lib/deniedError" {
  declare module.exports: any;
}

declare module "express-ipfilter/lib/ipfilter" {
  declare module.exports: any;
}

declare module "express-ipfilter/src/deniedError" {
  declare module.exports: any;
}

declare module "express-ipfilter/src/ipfilter" {
  declare module.exports: any;
}

declare module "express-ipfilter/test/ipfilter.spec" {
  declare module.exports: any;
}

// Filename aliases
declare module "express-ipfilter/example/app.js" {
  declare module.exports: $Exports<"express-ipfilter/example/app">;
}
declare module "express-ipfilter/example/routes/index.js" {
  declare module.exports: $Exports<"express-ipfilter/example/routes/index">;
}
declare module "express-ipfilter/example/routes/users.js" {
  declare module.exports: $Exports<"express-ipfilter/example/routes/users">;
}
declare module "express-ipfilter/Gruntfile.js" {
  declare module.exports: $Exports<"express-ipfilter/Gruntfile">;
}
declare module "express-ipfilter/index" {
  declare module.exports: $Exports<"express-ipfilter">;
}
declare module "express-ipfilter/index.js" {
  declare module.exports: $Exports<"express-ipfilter">;
}
declare module "express-ipfilter/lib/deniedError.js" {
  declare module.exports: $Exports<"express-ipfilter/lib/deniedError">;
}
declare module "express-ipfilter/lib/ipfilter.js" {
  declare module.exports: $Exports<"express-ipfilter/lib/ipfilter">;
}
declare module "express-ipfilter/src/deniedError.js" {
  declare module.exports: $Exports<"express-ipfilter/src/deniedError">;
}
declare module "express-ipfilter/src/ipfilter.js" {
  declare module.exports: $Exports<"express-ipfilter/src/ipfilter">;
}
declare module "express-ipfilter/test/ipfilter.spec.js" {
  declare module.exports: $Exports<"express-ipfilter/test/ipfilter.spec">;
}
