// flow-typed signature: 2900e66f73d15bf294715c8482e1478e
// flow-typed version: <<STUB>>/@versett/zafin-scripts_v1.3.1/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@versett/zafin-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@versett/zafin-scripts" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@versett/zafin-scripts/bin/index" {
  declare module.exports: any;
}

declare module "@versett/zafin-scripts/src/constants/cssProperties" {
  declare module.exports: any;
}

declare module "@versett/zafin-scripts/src/generate-component-sass-modules" {
  declare module.exports: any;
}

declare module "@versett/zafin-scripts/src/generate-config-imports" {
  declare module.exports: any;
}

declare module "@versett/zafin-scripts/src/helpers/fileBaseName" {
  declare module.exports: any;
}

declare module "@versett/zafin-scripts/src/helpers/fileExists" {
  declare module.exports: any;
}

declare module "@versett/zafin-scripts/src/helpers/getDirectories" {
  declare module.exports: any;
}

declare module "@versett/zafin-scripts/src/helpers/getLines" {
  declare module.exports: any;
}

declare module "@versett/zafin-scripts/src/helpers/getStyleVariableParts" {
  declare module.exports: any;
}

declare module "@versett/zafin-scripts/src/helpers/isFileClientSpecific" {
  declare module.exports: any;
}

declare module "@versett/zafin-scripts/src/helpers/listFilesOfType" {
  declare module.exports: any;
}

declare module "@versett/zafin-scripts/src/helpers/loadEnvVars" {
  declare module.exports: any;
}

declare module "@versett/zafin-scripts/src/helpers/outputFile" {
  declare module.exports: any;
}

declare module "@versett/zafin-scripts/src/helpers/relativeToAbsolutePath" {
  declare module.exports: any;
}

declare module "@versett/zafin-scripts/src/helpers/removeIfExists" {
  declare module.exports: any;
}

declare module "@versett/zafin-scripts/src/helpers/styleVariableMissorted" {
  declare module.exports: any;
}

declare module "@versett/zafin-scripts/src/helpers/styleVariablePartsValidators" {
  declare module.exports: any;
}

declare module "@versett/zafin-scripts/src/helpers/validateStyleVariableFormat" {
  declare module.exports: any;
}

declare module "@versett/zafin-scripts/src/validate-config-files" {
  declare module.exports: any;
}

// Filename aliases
declare module "@versett/zafin-scripts/bin/index.js" {
  declare module.exports: $Exports<"@versett/zafin-scripts/bin/index">;
}
declare module "@versett/zafin-scripts/src/constants/cssProperties.js" {
  declare module.exports: $Exports<
    "@versett/zafin-scripts/src/constants/cssProperties"
  >;
}
declare module "@versett/zafin-scripts/src/generate-component-sass-modules.js" {
  declare module.exports: $Exports<
    "@versett/zafin-scripts/src/generate-component-sass-modules"
  >;
}
declare module "@versett/zafin-scripts/src/generate-config-imports.js" {
  declare module.exports: $Exports<
    "@versett/zafin-scripts/src/generate-config-imports"
  >;
}
declare module "@versett/zafin-scripts/src/helpers/fileBaseName.js" {
  declare module.exports: $Exports<
    "@versett/zafin-scripts/src/helpers/fileBaseName"
  >;
}
declare module "@versett/zafin-scripts/src/helpers/fileExists.js" {
  declare module.exports: $Exports<
    "@versett/zafin-scripts/src/helpers/fileExists"
  >;
}
declare module "@versett/zafin-scripts/src/helpers/getDirectories.js" {
  declare module.exports: $Exports<
    "@versett/zafin-scripts/src/helpers/getDirectories"
  >;
}
declare module "@versett/zafin-scripts/src/helpers/getLines.js" {
  declare module.exports: $Exports<
    "@versett/zafin-scripts/src/helpers/getLines"
  >;
}
declare module "@versett/zafin-scripts/src/helpers/getStyleVariableParts.js" {
  declare module.exports: $Exports<
    "@versett/zafin-scripts/src/helpers/getStyleVariableParts"
  >;
}
declare module "@versett/zafin-scripts/src/helpers/isFileClientSpecific.js" {
  declare module.exports: $Exports<
    "@versett/zafin-scripts/src/helpers/isFileClientSpecific"
  >;
}
declare module "@versett/zafin-scripts/src/helpers/listFilesOfType.js" {
  declare module.exports: $Exports<
    "@versett/zafin-scripts/src/helpers/listFilesOfType"
  >;
}
declare module "@versett/zafin-scripts/src/helpers/loadEnvVars.js" {
  declare module.exports: $Exports<
    "@versett/zafin-scripts/src/helpers/loadEnvVars"
  >;
}
declare module "@versett/zafin-scripts/src/helpers/outputFile.js" {
  declare module.exports: $Exports<
    "@versett/zafin-scripts/src/helpers/outputFile"
  >;
}
declare module "@versett/zafin-scripts/src/helpers/relativeToAbsolutePath.js" {
  declare module.exports: $Exports<
    "@versett/zafin-scripts/src/helpers/relativeToAbsolutePath"
  >;
}
declare module "@versett/zafin-scripts/src/helpers/removeIfExists.js" {
  declare module.exports: $Exports<
    "@versett/zafin-scripts/src/helpers/removeIfExists"
  >;
}
declare module "@versett/zafin-scripts/src/helpers/styleVariableMissorted.js" {
  declare module.exports: $Exports<
    "@versett/zafin-scripts/src/helpers/styleVariableMissorted"
  >;
}
declare module "@versett/zafin-scripts/src/helpers/styleVariablePartsValidators.js" {
  declare module.exports: $Exports<
    "@versett/zafin-scripts/src/helpers/styleVariablePartsValidators"
  >;
}
declare module "@versett/zafin-scripts/src/helpers/validateStyleVariableFormat.js" {
  declare module.exports: $Exports<
    "@versett/zafin-scripts/src/helpers/validateStyleVariableFormat"
  >;
}
declare module "@versett/zafin-scripts/src/validate-config-files.js" {
  declare module.exports: $Exports<
    "@versett/zafin-scripts/src/validate-config-files"
  >;
}
